# Generated by Django 3.1.4 on 2020-12-12 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoycostsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='スタッフ名')),
                ('hour', models.IntegerField(verbose_name='勤務時間')),
                ('wage', models.IntegerField(verbose_name='時給')),
                ('fixedsalary', models.IntegerField(verbose_name='固定給')),
                ('allowance', models.IntegerField(blank=True, null=True, verbose_name='手当')),
                ('mounth_allowance', models.IntegerField(blank=True, null=True, verbose_name='月末手当')),
                ('salary', models.IntegerField(blank=True, default=0, null=True, verbose_name='給料')),
                ('salary_total', models.IntegerField(blank=True, default=0, null=True, verbose_name='給料トータル')),
                ('yes_or_no', models.IntegerField(blank=True, null=True, verbose_name='これが最後の入力になりますか？')),
            ],
        ),
        migrations.CreateModel(
            name='GirlscostsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='スタッフ名')),
                ('hour', models.IntegerField(verbose_name='勤務時間')),
                ('wage', models.IntegerField(verbose_name='時給')),
                ('drinkbag', models.IntegerField(blank=True, null=True, verbose_name='ドリンクバック(別)')),
                ('drinkbag_count', models.IntegerField(blank=True, null=True, verbose_name='ドリンクバックの杯数(別)')),
                ('drinkbag_in', models.IntegerField(blank=True, null=True, verbose_name='ドリンクバック(込み)')),
                ('drinkbagin_count', models.IntegerField(blank=True, null=True, verbose_name='ドリンクバックの杯数(込み)')),
                ('bag', models.IntegerField(blank=True, null=True, verbose_name='指名料のバック')),
                ('champagne_bag', models.IntegerField(blank=True, null=True, verbose_name='シャンパンバック')),
                ('salary', models.IntegerField(blank=True, default=0, null=True, verbose_name='給料')),
                ('salary_total', models.IntegerField(blank=True, default=0, null=True, verbose_name='給料トータル')),
                ('yes_or_no', models.IntegerField(blank=True, null=True, verbose_name='これが最後の入力になりますか？')),
            ],
        ),
        migrations.CreateModel(
            name='ProfitModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salestotal', models.IntegerField(blank=True, null=True)),
                ('boyscosts', models.IntegerField(blank=True, null=True)),
                ('girlscosts', models.IntegerField(blank=True, null=True)),
                ('costs', models.IntegerField(blank=True, null=True)),
                ('profit', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingcostsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopping_costs', models.IntegerField(verbose_name='買い物代')),
                ('others', models.IntegerField(blank=True, null=True, verbose_name='他にかかった費用')),
                ('profit', models.IntegerField(blank=True, null=True, verbose_name='臨時収入')),
                ('shopping_total', models.IntegerField(blank=True, default=0, null=True, verbose_name='出費総額')),
                ('yes_or_no', models.IntegerField(blank=True, null=True, verbose_name='これが最後の入力になりますか？')),
            ],
        ),
    ]
