# Generated by Django 3.1.1 on 2021-02-06 08:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('costsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profitmodel',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
