# Generated by Django 3.1.1 on 2021-02-23 19:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('costsapp', '0002_profitmodel_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boycostsmodel',
            name='yes_or_no',
        ),
        migrations.RemoveField(
            model_name='girlscostsmodel',
            name='yes_or_no',
        ),
        migrations.RemoveField(
            model_name='shoppingcostsmodel',
            name='yes_or_no',
        ),
        migrations.AddField(
            model_name='boycostsmodel',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='girlscostsmodel',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='shoppingcostsmodel',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='profitmodel',
            name='boyscosts',
            field=models.IntegerField(blank=True, null=True, verbose_name='ボーイの給料合計'),
        ),
        migrations.AlterField(
            model_name='profitmodel',
            name='costs',
            field=models.IntegerField(blank=True, null=True, verbose_name='買い物代などの他費用'),
        ),
        migrations.AlterField(
            model_name='profitmodel',
            name='girlscosts',
            field=models.IntegerField(blank=True, null=True, verbose_name='キャストの給料合計'),
        ),
        migrations.AlterField(
            model_name='profitmodel',
            name='profit',
            field=models.IntegerField(blank=True, null=True, verbose_name='今日の利益'),
        ),
        migrations.AlterField(
            model_name='profitmodel',
            name='salestotal',
            field=models.IntegerField(blank=True, null=True, verbose_name='今日の売上'),
        ),
    ]
