# Generated by Django 3.1.1 on 2021-03-10 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costsapp', '0003_auto_20210224_0405'),
    ]

    operations = [
        migrations.AddField(
            model_name='profitmodel',
            name='people',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
